2019-11-10 23:21:07.547 [error] <0.1637.0>@hackney_metrics:get_engine:26 gen_server tzdata_release_updater terminated with reason: bad argument in call to ets:lookup_element(hackney_config, mod_metrics, 2) in hackney_metrics:get_engine/0 line 26
2019-11-10 23:21:07.563 [error] <0.1637.0>@hackney_metrics:get_engine:26 CRASH REPORT Process tzdata_release_updater with 0 neighbours crashed with reason: bad argument in call to ets:lookup_element(hackney_config, mod_metrics, 2) in hackney_metrics:get_engine/0 line 26
2019-11-10 23:21:07.563 [error] <0.1631.0>@hackney_metrics:get_engine:26 Supervisor {<0.1631.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Tzdata.ReleaseUpdater' started with 'Elixir.Tzdata.ReleaseUpdater':start_link() at <0.1637.0> exit with reason bad argument in call to ets:lookup_element(hackney_config, mod_metrics, 2) in hackney_metrics:get_engine/0 line 26 in context child_terminated
